Nmbrs/tf-modules

- azure/appservice/data.tf
- azure/appservice/local.tf
- azure/appservice/main.tf
- azure/appservice/output.tf
- azure/appservice/terraform.tf
- azure/appservice/variables.tf
- initial version of the app service plan templates.
- added app service basic setup
- removed the service variable since we no longer needed.
- removed the tags input variable, since we can reuse the other ones to fill the map.
- replaced the owner with squad variable.
- added resource "azurerm_application_insights" "example"
- fixed the output resource name.
- added reserved property to the app service plan since we are using Linux instances.
- added azure log analytics workspace that is the new app insights new gen.
- fixed a typo.
- removed the workspace tier and let it default.
- removed data entries.
> Azure App Service Basic Version

- azure/appservice/main.tf
Terraform Cloud is throwing the following error
Accordingly, with Terraform documentation, the `ftps` property belongs to the resource root.
> azure app service site config

- azure/appservice/main.tf
Removed the `ftps_state` property because it's throwing exceptions when applying or planning, despite the fact that it's compliant with docs  the latest version
Without removing the property, we cannot provision app service on azure.
Local cli.
> ftps removed from azure appservice

- azure/appservice-windows/main.tf
- azure/appservice-windows/terraform.tf
- azure/appservice-windows/variables.tf
- azure/resource-group/main.tf
- azure/resource-group/variables.tf
Adding Subnet and VNet Resources to app service module and enabling the VNet Integration in the template
I have kept the address space and the address prefix hardcoded for now since i got issue when trying to add it as a variable, was not able to fix it so keeping this for now till i find the solution. 
Please add your comments for any changes needed or something i might have forgotten i will update them.
Ran Locally and tested out. Below is the terraform Plan for the change. 
```
+ resource "azurerm_app_service" "app" {
+ app_service_plan_id               = (known after apply)
+ app_settings                      = (known after apply)
+ client_affinity_enabled           = false
+ client_cert_enabled               = false
+ client_cert_mode                  = (known after apply)
+ …
```
> adding subnets and Vnet integration for the appservice module

- azure/resource-group/local.tf
- azure/resource-group/main.tf
- azure/resource-group/output.tf
- azure/resource-group/variables.tf
The region is now handled as a variable instead of a local, to decouple the hard dependency.
In case we want to support multi regions, and because it should be enforced through policy instead.
```diff
+ resource "azurerm_resource_group" "rg" {
+ id       = (known after apply)
++      + location = "westeurope"
+ name     = "rg-heimdall-aks-dev"
+ tags     = {
+ "Country"     = "nl"
+ "Environment" = "dev"
+ "Product"     = "internal"
+ "Squad"       = "infra"
+ "datadog"     = "monitored"
}
}
```
n/a
> maint: moved region to a variable

- azure/storage_account/README.md
- azure/storage_account/data.tf
- azure/storage_account/main.tf
- azure/storage_account/output.tf
- azure/storage_account/terraform.tf
- azure/storage_account/variables.tf
The idea of this PR was to create a first version of the storage account  to be used in our terraform services
In our previous implementation, we were using the `azurerm_storage_account` module, but figuring out how to name it was a task to the developer. Also is important to keep in mind that the developer must remember 2 things:
-  storage account name cannot be longer than 24 characters
-  storage account name must be unique.
The module removes the burden of thinking about the module naming and allow us to read the `location` and `resource_group_name` from the resource group.
A quick way to test it:
1) create a new folder in your computer and copy the `storage_account` folder to it
2) Create a new tf file (`main.tf` for example) and add the code below referencing the 'storage_account' …
> feat(storage-account): create storage account module

- azure/storage_account/README.md
- azure/storage_account/output.tf
The main goal of this PR is to add the connection strings and access keys for the storage account
Since we need to output the connection string, access key and storage account name to the application pipeline, we need to expose them as outputs. In this PR the follow outputs were made available:
- primary access key
- secondary access key
- primary connection string
- secondary connection string
1. Create a new folder in your computer and copy the storage_account folder to it
2. Create a new tf file (main.tf for example) and add the code below referencing the 'storage_account' module
```hcl
terraform {
azurerm = {
version = "=2.98.0"
}
}
}
features {
}
}
type        = …
```
> feat(storage-account): add connection string and access key outputs

- azure/custom-domain-binding/main.tf
Switched the variable used to create the cname, because the wildcard wasn't being created.
The wildcard cname, that redirects all traffic to the web, wasn't being created.
> fix(ssl binding): variable usage

- azure/storage_account/README.md
- azure/storage_account/local.tf
- azure/storage_account/main.tf
- azure/storage_account/output.tf
- azure/storage_account/terraform.tf
- azure/storage_account/variables.tf
The main goal of this PR is to update the validation of the storage account input variables, providing a development interface safer / easier to use
- Transformed the storage-account name to lowercase inside the module
- Added validations for the variables:
- `name`
- `location`
- `resource_group_name`
- `tags`
- Updated indentation to follow canonical format
1. At the root of the `tf-module` repository, create a `main.tf` file with the following code:
```hcl
terraform {
azurerm = {
}
}
}
features {
}
}
source      = "../tf-modules/azure/resource-group" …
```
> feat(storage-account):add variables validation

- azure/keyvault/README.md
- azure/keyvault/variables.tf
The main goal of this PR is to create validation mechanisms for the list of policy objects designed for the keyvault. The validation mechanism must allow:
- empty list of policies
- Filled list of policies, but each property needs to be validated:
- `name` must be a non-empty string
- `object_id` must be a non-empty string
- `type` valid values must be readers or writers
- Updated `README.md` to explain how to use the policies.
- Added missing input variables in the `README.md`.
- Created a validation logic for the `name` property that only allows non-empty strings.
- Created a validation logic for the `object_id` property that only allows non-empty strings.
- Created a validation logic for …
> feature(keyavualt): add keyvault policies validation

- azure/keyvault/main.tf
The main goal of this PR is to update the default network acls behavior to allow access to the keyvault from any network.
If we decide to limit access to all networks at this time, the applications will not be able to access the keyvault effectively.
As a result, while we move the resources to Terraform, access will be allowed from all networks to avoid any incompatibilities. 
- disable tfsec rule `azure-keyvault-specify-network-acl` failed
- Update network ACLS  to allow access to the keyvault from any network.
>⚠️  The tfsec rule ` azure-keyvault-specify-network-ac` in terms of security is critical but if we implement the "fix", the apps will not access the keyvaults
1. Create a new tf …
> feature(keyvault): update network acls default behavior

- azure/resource-group/main.tf
The main purpose of this PR is to remove the environment from the resource group name, since the environments dev and test share the same resource-group.
- Updated `resouce-group` naming: the name is composed by `rg` prefix and the `name` variable.
1. At the root of the `tf-module` repository, create a `main.tf` file with the following code:`
```hcl
terraform {
azurerm = {
}
}
}
features {
}
}
source      = "./azure/resource-group"
name        = "new-pr-demo"
environment = "Dev" …
```
> feat(resource-group): remove environment var from naming convention

- azure/keyvault/README.md
- azure/keyvault/local.tf
- azure/keyvault/variables.tf
The main goal of this PR is to include an environment variable to keyvault module instead of using the environment tag provided by the group. By doing sos, the environment provided in existing resource-groups tags will not affect the keyvault name.
- Add environment variable to keyvault module
1. At the root of the `tf-module` repository, create a `main.tf` file with the following code:`
```hcl
terraform {
azurerm = {
}
}
}
features {
}
}
source      = "./azure/resource-group"
name        = "heimadall-demo"
environment = "Dev" …
```
> feature(keyvault): add environment variable to keyvault module

- azure/keyvault/variables.tf
The main goal of this PR is to update the validation of the AD `ObjectID` present in the keyvault policies.
To validate the ObjectID, the following regex pattern was used: 
`^[0-9a-fA-F]{8}\\b-[0-9a-fA-F]{4}\\b-[0-9a-fA-F]{4}\\b-[0-9a-fA-F]{4}\\b-[0-9a-fA-F]{12}$`
ObjectIDs basically follows the UUID pattern (32 characters in hexadecimal notation):
- first 8 characters - 8 hexadecimal chars separated by a hyphen.
- next 4 characters - 4 hexadecimal chars separated by a hyphen.
- next 4 characters - 4 hexadecimal chars separated by a hyphen.
- next 4 characters - 4 hexadecimal chars separated by a hyphen.
- final 12 characters - 12 hexadecimal chars.
Below is an example UUID:
*b22fc8e6-b18d-11ec-b909-0242ac120002*
What kind of change …
> feature(keyvault): add uuid regex pattern to validate object id

- .github/workflows/release-please.yml
The idea is to have a release _pull request_ that is updated when _pull requests_ are merging, and when ready to release, the team just needs to merge the release _pull request_.
To achieve, we will rely on Google release-please action. More information can be found [here](https://github.com/googleapis/release-please).
> feat: added release workflow for automation

- azure/resource_group/terraform.tf
The main goal of this PR is to update the providers used in the `resouce_group` module:
- azurerm: https://registry.terraform.io/providers/hashicorp/azurerm/3.5.0
As described [here](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/guides/3.0-upgrade-guide), Terraform will now check for Resources nested within a Resource Group prior to deletion of the resource group. If any items are found, an error will be raised. This behavior is configurable in the features block, but was previously disabled by default. In 3.0, this behavior will be enabled by default. 
1. Create a new tf file (main.tf for …
> build(resource_group): update azurerm and caf providers

- azure/key_vault/README.md
- azure/key_vault/local.tf
- azure/key_vault/terraform.tf
The main goal of this PR is to update the providers used in the `key_vault` module:
- azurerm: https://registry.terraform.io/providers/hashicorp/azurerm/3.5.0
- Updated secrets full permissions list to comply with the new implemented validators. The new valid options can be seen here: 
https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/key_vault_access_policy#secret_permissions
- Updated certificate full permissions list to comply with the new implemented validators. The new valid options can be seen here: 
https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/key …
> build(key_vault): update azurerm and caf providers

- azure/dns_zone/terraform.tf
- azure/key_vault/terraform.tf
- azure/resource_group/terraform.tf
- azure/storage_account/terraform.tf
The main goal of this PR is to update how modules manage providers and terraform versions, ensuring that all modulesupports patches and minor versions updates.
The Terraform provider version was configured to support any version between 1.0.0 and 2.0.0 (no major version updates) and the azurerm provider was configured to support any version higher than 3.6 using [this](https://learn.hashicorp.com/tutorials/terraform/versions?in=terraform/1-0#terraform-version-constraints) guide. 
N/A
1. Create a new tf file (main.tf for example) at the root of this repo in your working directory and add the code below referencing  `key_vault`, `dns_module`, `resource_group` and `storage_account` module. …
> build: update providers versioning system

- azure/key_vault/main.tf
- azure/key_vault/variables.tf
The main goal of this PR is to fix a bug present in the elements of the policy array which are referenced in tfstate by their index rather than their name.
This is especially problematic when an element in the middle of the array is removed, changing the original indexes of the next policy. As a result, Terraform will attempt to recreate all subnets for which the index has changed.
Also, as a "collateral damage", this PR adds uniqueness name validation for the policies.
1 . Create a new tf file (main.tf for example) at the root of this repo in your working directory and add the code below:
```hcl
terraform {
required_version = ">= 1.0.0, < 2.0.0"
}
features {
}
}
module …
```
> fix(key_vault): update policies index based references in tfstate

- azure/virtual_network/main.tf
- azure/virtual_network/variables.tf
The main goal of this PR is to fix a bug  introduced in the release `7.0.0` (PR #129 ):  the elements of the subnets array are referenced in tfstate by their index rather than their name.
This is especially problematic when an element in the middle of the array is removed, changing the original indexes of the next vnets. As a result, Terraform will attempt to recreate all subnets for which the index has changed.
Also, as a "colateral damage", this PR adds uniqueness name validation for the subnets.
N/A
1 . Create a new tf file (main.tf for example) at the root of this repo in your working directory and add the code below:
```hcl
terraform {
required_version = ">= 1.0.0, < 2.0.0"
}
provider …
```
> fix(virtual_netowrk): update subnet index based references in tfstate

- azure/key_vault/output.tf
The main goal of this PR is to add readers and writers policies outputs, making this information available for automation systems and tools in a service level.
- Added readers access policies output  `output.tf` file
- Added writers access policies output  `output.tf` file
```hcl
terraform {
}
features {
}
}
name        = "pr-testffs"
product     = "not_applicable"
extra_tags = {
managed_by = "terraform" …
```
> feat(key_vault): add readers and writers policies outputs

- azure/resource_group/README.md
- azure/resource_group/local.tf
- azure/resource_group/main.tf
- azure/resource_group/variables.tf
The main goal of this PR is to update the `resource_group` module, so it can adhere to nmbrs tagging strategy and  the currently implemented azure policies.
- Added the following default_tags:
- category. Default value: `not_applicable`
- country. Default value: `global`
- managed_by. The value is always terraform.
- owner. Default value: `not_applicable`
- status. Default value: `life_cycle`
- Removed the following default tags:
- Provisioned_By
- Squad
- All default tags keys and values are in small case.
1 . Create a new tf file (main.tf for example) at the root of this repo in your working directory and add the code below:
```hcl
terraform {
}
module …
```
> feat(resource_group): update resource group tags to adhere to azure policy

- github/repositories/main.tf
- github/repositories/variables.tf
The main goal of this to change the names of the indexes used by github's repositories, preventing components that are written identically but with different indentations from being recognized as unique elements.
- Github repositories  with the same name, but with different cases or indentation, will not be considered distinct elements in terraform state.
```hcl
terraform {
}
variable "github_token" {
sensitive = true
}
variable "github_owner" {
sensitive = true
default   = "nmbrs"
}
module …
```
> fix(github): trim spaces and lower case repository indexes

- azure/key_vault/main.tf
- azure/key_vault/terraform.tf
- azure/key_vault/variables.tf
The main goal of this to change the names of the indexes used by the key vault's access policies, preventing components that are written identically but with different indentations from being recognized as unique elements.
- The access policies indexes with the same name, but with diffent cases or indentation, will not be considered distinct elements in terraform state
```hcl
terraform {
}
name        = "pr-test"
product     = …
```
> fix(key_vault): trim spaces and lower case acess policies indexes

- azure/key_vault/main.tf
The main goal of this PR is to ignore the tags `created_at` and `updated_at` managed by the custom Azure's policies implemented at nmbrs
1. Go to tf-service and pick-up a service with a recently deployed key_vaults. A good candidate would be `invoicing` service from `dev` environment.
2. Initialize terraform (`terraform init`) and run the speculative plan (`terraform plan`). The tags `created_by` and `updated_at` should be replaced by a null value accordingly with tf-plan
3. At the `main.tf` from `invoicing` service, replace the remote reference in the `source` paramater with the local absolute path of the `key_vault` from this branch, as shown in the example below:
```hcl
module …
```
> feat(key_vault): ignore updated_at and created_at tags

- azure/key_vault/local.tf
The main goal of this PR is to remove the `ProvisionedBy` tag and add the `managed_by` tag, ensuring that the key_vault module complies with Nmbrs tagging strategy
- Remove `ProsivisonedBy` tag
- Add `managed_by`tag
```hcl
terraform {
}
name        = "pr-test"
product     = "not_applicable"
extra_tags = {
managed_by = "terraform"
category   = "not_applicable"
owner      = "not_applicable"
status     = "temporary"
}
}
module …
```
> feat(key_vault): add managed_by tag

- azure/key_vault/local.tf
- azure/key_vault/main.tf
The main goal of this PR is to include the properties `key_permissions` and `storage_permissions` in kv's access policies, ensuring that no diffs relating to these keys appear in speculative plans. 
- Diffs related to `key_permissions` and `storage_permissions` should not be displayed in the speculative plan
1. In `tf-services`, select the invoicing service from dev environment and change the key_vault module, pointing to your local tf-module. 
2. Run terraform plan and the speculative plan should not display diffs related with `key_permissions` and `storage_permissions`
> feat(key_vault): add key and storage permissions to access policies

- azure/dns_records/main.tf
- azure/dns_records/output.tf
- azure/dns_records/terraform.tf
- azure/dns_records/variables.tf
The main goal of this PR is to update the dns_records supporting indexed based data in terraform state and also updating the `azurerm` provider to version v3.x
- In terraform state the dns records indexes are named based instead of record_named based
Create a new tf file (main.tf for example) at the root of this repo in your working directory and add the code below:
```hcl
terraform {
}
features {
}
}
name        = "pr-testffs"
product     = "not_applicable"
extra_tags = {
managed_by = "terraform"
category   = "not_applicable"
owner      = …
```
> feature(dns_records): update dns_records module

- azure/storage_account/local.tf
This pull request replaces the older ```ProvisionedBy``` tag key with the new one - ```managed_by```, so it can be compliant with Nmbrs tag strategy.
This fixes the Jira ticket NMBRS-43317
> fix(storage_account): modified the default tag to align with tag strategy NMBRS-43317

- azure/key_vault/main.tf
The main goal of this PR is to fix the precedence of merging Azure tags for `key_vault` modules. The following rule should be applied when merging tags
1. Read and inherit tags from the resource groups that contains the resource 
2. Use default tags and replace values for any common tag inherited from resource group
3. Use tags from the parameter `extra_tags`  and replace values for any common tag inherited from resource group or default tags
- Updated the precedence order for merging Azure tags in the module. The merging strategy was updated from: `default_tags -> resource_group inheritance  ->  extra_tags` to `resource_group inheritance -> default_tags ->  extra_tags`
Create a new tf file …
> fix(key_vault): update default tags precedence

- azure/storage_account/main.tf
The main goal of this PR is to fix the precedence of merging Azure tags for `storage_account` modules. The following rule should be applied when merging tags
1. Read and inherit tags from the resource groups that contains the resource 
2. Use default tags and replace values for any common tag inherited from resource group
3. Use tags from the parameter `extra_tags`  and replace values for any common tag inherited from resource group or default tags
- Updated the precedence order for merging Azure tags in the module. The merging strategy was updated from: `default_tags -> resource_group inheritance  ->  extra_tags` to `resource_group inheritance -> default_tags ->  extra_tags`
Create a new tf …
> fix(storage_account): update default tags precedence

- azure/resource_group/main.tf
The main goal of this PR is to fix the precedence of merging Azure tags for `resource_group` modules. The following rule should be applied when merging tags
1. Use default tags and replace values for any common tag inherited from resource group
2. Use tags from the parameter `extra_tags`  and replace values for any common tag inherited from default tags
- Updated the precedence order for merging Azure tags in the module. The merging strategy was updated from: `extra_tags ->  extra_tags` to `default_tags ->  extra_tags`
N/A
N/A
> fix(resource_group): update default tags precedence

- azure/virtual_network/local.tf
- azure/virtual_network/main.tf
The main goal of this PR is to fix the precedence of merging Azure tags for `vnet` modules. The following rule should be applied when merging tags
1. Read and inherit tags from the resource groups that contains the resource 
2. Use default tags and replace values for any common tag inherited from resource group
3. Use tags from the parameter `extra_tags`  and replace values for any common tag inherited from resource group or default tags
- Updated the precedence order for merging Azure tags in the module. The merging strategy was updated from: `default_tags -> resource_group inheritance  ->  extra_tags` to `resource_group inheritance -> default_tags ->  extra_tags`
Create a new tf file …
> fix(virtual_network): update tag precedence vnet

- azure/virtual_network/main.tf
- azure/virtual_network/variables.tf
The main goal of this pull request is to replace the subnet parameters `enforce_private_link_service_network_policies` and `enforce_private_link_endpoint_network_policies` marked for deprecation for the future new major release of AzureRM module
- [] The documentation was updated (`README.md`, `CHANGELOG.md`, etc.).
N/A
While creating a plan, no deprecation warning should be displayed
> feat(virtual_network): update subnet parameters to prevent future deprecation

- azure/cosmos_db/local.tf
- azure/cosmos_db/main.tf
- azure/cosmos_db/terraform.tf
- azure/cosmos_db/varaiables.tf
The main goal of this pull request is to rename the `cosmo_db` module to `cosmos_db` module, so we can make it comply with Microsoft naming convention for the product, avoiding confusion throughout the development process.
N/A
N/A
N/A
> refactor(cosmos_db): rename cosmos_db module

- general/environment/README.md
- general/environment/outputs.tf
- general/environment/terraform.tf
- general/environment/variables.tf
The main purpose of this PR is to introduce a new Terraform module named environment that will handle the logic for selecting and validating the environment in which resources are deployed. The environment module will take a single input variable named environment that accepts only the values dev, test, prod, and sand. The module will output a single variable named name that will contain the selected environment.
This change will transfer the responsibility of environment validation from each individual Terraform module to the environment module, allowing for better isolation of the environment logic and making it easier to maintain and update the validation rules in one central location. Additionally, the isolation of the environment validation in a separate module will allow for the use …
> feat(environment): create environment module

- azure/location/README.md
- azure/location/main.tf
- azure/location/outputs.tf
- azure/location/terraform.tf
- azure/location/variables.tf
The main purpose of this PR is to create a location module that allows for the isolation of location validation and the extraction of location logic from other Terraform modules. This change will transfer the responsibility of validation from individual modules to the location module and Azure policies, making the overall codebase more modular and maintainable. 
Additionally, by providing a standalone location module, other modules can more easily reference and utilize the location validation logic, reducing duplication and increasing code reuse. Overall, this PR aims to improve the organization and maintainability of the codebase, while also streamlining the validation process.
Creation of …
> feat(location): create location module

- azure/virtual_network/README.md
- azure/virtual_network/terraform.tf
- azure/virtual_network/variables.tf
The main purpose of this PR is to remove the validation of the environment from the `virtual_network` level. This change aims to transfer the responsibility of validating the environment and location to the Azure policies and the new modules location and environment. 
By implementing this change, we will make the virtual_network more focused on its main purpose, and also make it less prone to errors by removing unnecessary validation code. This will also make it easier to maintain and understand the codebase in the long run.
- Removed the validation of the `envrionment` variable.
1. Create a new tf file (main.tf for example) at the root of this repo in your working directory and add the code …
> feat(virtual_network): remove environment validation

- azure/private_dns_zone/README.md
- azure/private_dns_zone/main.tf
- azure/private_dns_zone/terraform.tf
- azure/private_dns_zone/variables.tf
The main goal of this PR is to enable private dns zones to be linked to virtual networks using `virtual network links`. A virtual network can be linked to a private DNS zone as a registration or as a resolution virtual network.
When [creating a link](https://learn.microsoft.com/en-us/azure/dns/private-dns-getstarted-portal#link-the-virtual-network) between a private DNS zone and a virtual network. You have the option to enable [autoregistration](https://learn.microsoft.com/en-us/azure/dns/private-dns-autoregistration). With this setting enabled, the virtual network becomes a registration virtual network for the private DNS zone.
If you choose to link your virtual network with the private DNS zone without autoregistration, the virtual network is treated as a resolution virtual network …
> feat(private_dns_zone): add vnet links

- azure/key_vault/terraform.tf
The main goal of this pull request is to remove the azurerm provider's configurations from the key_vault module, to allow for the implementation of a JSON-friendly approach. By removing the provider's configuration, it will be possible to create for loops and implement our module in a list of values in the JSON.
N/A
N/A
N/A
> feat(key_vault): remove provider configs to allow the use of for_each loops

- azure/resource_group/main.tf
- azure/resource_group/terraform.tf
The main goal of this pull request is to remove the caf provider's configurations from the module,  removing the naming dependency inside the module.
N/A
N/A
N/A
> feature(resource_group): remove caf dependency

- azure/storage_account/main.tf
The main goal of this PR is to remove the `queue_properties` implementation from the storage account module as it prevent us to create certain kinds of storage accounts. 
N/A
N/A
> feature(storage-account): remove queue properties

- azure/virtual_network/README.md
- azure/virtual_network/outputs.tf
The main goal of this PR is to update the outputs of the vnet module to allow the consumption of the subnet name as an output.
- Added the new output subnets containing a list of subnet's data containing the subnet name and id
N/A
N/A
> feature(virtual_network): add subnet name output

- azure/app_service/local.tf
- azure/app_service/variables.tf
The main goal of this PR is to update the naming logic for the app_services, preventing further confusion while composing the app_service name and service_plan_name
> fix(app_service): update app service naming logic

- azure/service_bus/main.tf
The main goal of this PR is to fix all validations for the `capacity` parameter for the `service_bus` module. The validations should follow the rules below:
- For the `Basic` tier, capacity should be 0.
- For the `Standard` tier, capacity should be 0.
- Valid options for capacity when using the `Premium` tier are: 1, 2, 4, 8, 16
The capacity (message units) is being validated as shown in the rules below
- For the `Basic` tier, capacity should be 0.
- For the `Standard` tier, capacity should be 0.
- Valid options for capacity when using the `Premium` tier are: 1, 2, 4, 8, 16
> fix(service_bus): update capacity validations for all tiers

- azure/nat_gateway/README.md
- azure/nat_gateway/local.tf
- azure/nat_gateway/main.tf
- azure/nat_gateway/variables.tf
The main goal of this PR is to update the naming logic for the nat_gateway, enabling it to comply with the following rule:
- nat gateway: `ng-<application/workload><location><environment><###>`
- public ip: `pip-ng-<application/workload><location><environment><###>`
- Added the `naming_sequential_number` parameter
N/A
> feature(nat_gateway): update naming logic

- azure/resource_group/main.tf
The main goal of this PR is to ignore the tags after creating the resource group, allowing automation tools to manipulate it freely through configuration workflows
- ignore resource group tags after creating it
> feature(resource_group): ignore tags after creation process

- azure/storage_account/README.md
- azure/storage_account/terraform.tf
The main goal of this PR is to remove the unused CAF provider reference from the `key_vault` module
N/A
N/A
> feature(storage_account): remove caf provider reference

- azure/service_bus/README.md
- azure/service_bus/local.tf
- azure/service_bus/main.tf
- azure/service_bus/output.tf
The main goal of this PR is to update `service_bus` naming logic, replacing the parameter `name` in favor of the `workload`
> feature(service_bus): replace name parameter in favor of workload

- azure/log_analytics_workspace/README.md
- azure/log_analytics_workspace/local.tf
- azure/log_analytics_workspace/output.tf
- azure/log_analytics_workspace/variables.tf
The main goal of this PR is to update `log_analytics_workspace` naming logic, replacing the parameter `name` in favor of the `workload`
> feature(log_analytics_workspace): replace name parameter in favor of workload

- azure/application_insights/README.md
- azure/application_insights/local.tf
- azure/application_insights/output.tf
- azure/application_insights/variables.tf
The main goal of this PR is to update `application_insights` naming logic, replacing the parameter `name` in favor of the `workload`
> feature(application_insights): replace name parameter in favor of workload

- azure/redis_cache/README.md
- azure/redis_cache/local.tf
- azure/redis_cache/main.tf
- azure/redis_cache/outputs.tf
- azure/redis_cache/variables.tf
The main goal of this PR is to update `redis_cache` naming logic, replacing the parameter `name` in favor of the `workload`
> feature(redis_cache): replace name parameter in favor of workload

- azure/redis_cache/variables.tf
The main goal of this PR is to fix the validation of the redis module replacing the `name` parameter for the `workload` parameter in the validations of the workload
> fix(redis_cache): fix workload parameter validation

- azure/key_vault/README.md
- azure/key_vault/main.tf
- azure/key_vault/variables.tf
The main goal of this PR is to enable purge protection by default in the key vaults
- Purge protection is enabled by default in the key vault
N/A
N/A
> feature(key_vault): enable purge protection by default

- azure/virtual_network_peering/local.tf
- azure/virtual_network_peering/main.tf
The main goal of this PR is to remove the `peering` prefix of the resource to accommodate bigger vnet names
> feature(virtual_network_peering): remove peering prefix from resource naming

- azure/storage_account/README.md
- azure/storage_account/main.tf
- azure/storage_account/terraform.tf
The main goal of this PR is to update the parameter `enable_https_traffic_only` to ` https_traffic_only_enabled` as it was deprecated by the `azurerm`  provider v4.x
No changes
Create a new tf file (main.tf for example) at the root of this repo in your working directory and add the code below:
```hcl
terraform {
azurerm = {
version = "~> 3.116"
}
}
required_version = "~> 1.5.0"
}
}
module "storage" {
source              = "./azure/storage_account"
name                = "satfdemo"
environment         = var.environment
resource_group_name = var.resource_group_name
account_kind        = "Storage"
account_tier        = …
```
> feature(storage_account): update https only parameter

- azuredevops/project/README.md
- azuredevops/project/data.tf
- azuredevops/project/main.tf
- azuredevops/project/terraform.tf
- azuredevops/project/variables.tf
The main goal of this PR is to allow the possibility of assign multiple owners to the same Azure DevOps project
- Add single/multiple readers groups
- Add single/multiple readers contributors
- Add single/multiple administrator groups
> feature(azuredevops_project): add multiple ownerships
