Nmbrs/tf-modules

azure/appservice/main.tf
azure/appservice/output.tf
azure/appservice/variables.tf

The product tag added to the resource tag list since it's mandatory in Nmbrs.

added product tag to the tags list

---

azure/appservice/main.tf

Added the environment value as a resource prefix at the end to avoid global unique conflicts.

Resource Environment Prefix

---

azure/keyvault/local.tf
azure/keyvault/main.tf
azure/keyvault/output.tf
azure/keyvault/terraform.tf
azure/keyvault/variables.tf

This pull request provides an all new module that allows services to create Azure key vaults. This is the first iteration since the key vault is still not secure enough to go to production and private endpoints and firewall policies must be revisited and added to the terraform templates.

Adding Azure Key Vault Terraform Module

---

azure/nat-gateway/main.tf
azure/nat-gateway/variables.tf

I changed the variable type and added a for_each on the nat association.
This allows to create a nat gateway with several subnets associated
Solve the problem of the nat gateway creation with several subnets associated using variables
cli locally
- [x ] Breaking change (fix or feature that would cause existing functionality to change)
- [x ] My code follows the code style of this project.

changed variable type and added a for_each on the association

---

.gitignore
azure/appservice/main.tf
azure/appservice/output.tf
azure/appservice/terraform.tf
azure/appservice/variables.tf
azure/resource-group/data.tf
azure/resource-group/local.tf
azure/resource-group/main.tf
azure/resource-group/output.tf
azure/resource-group/terraform.tf
azure/resource-group/variables.tf

The Azure resource group as a dedicated module where constraints and nmbrs naming convention rules can be enforced.
Separation of concern, since it was embedded with the provisioning of an azure app service and abstraction.
Using the Heimdall project pointing to the branch.
Terraform Cloud Run: https://app.terraform.io/app/Nmbrs/workspaces/heimdall-test/runs/run-eFCHcbFiGSvU4pdk

Resource Group Module

---

azure/appservice-windows/output.tf

Fix small bug for the output value name

fix minor bug on the output file

---

azure/appservice-windows/main.tf

fixing some typo and removing the stack attribute which is not needed

fixing some typo and removing the stack attribute which is not needed

---

azure/appservice-windows/main.tf

The app service module for the .NET as incorrect settings.
To fix the module.
Tested local with a dummy service.
```
+ resource "azurerm_application_insights" "app" {
+ app_id                                = (known after apply)
+ application_type                      = "web"
+ connection_string                     = (sensitive value)
+ daily_data_cap_in_gb                  = (known after apply)
+ daily_data_cap_notifications_disabled = (known after apply)
+ disable_ip_masking                    = false
+ id                                    = (known after apply)
+ instrumentation_key                   = (sensitive value)
+ internet_ingestion_enabled            = true
+ internet_query_enabled                = true
+ local_authentication_disabled         = false
+ location …
```

removed and replaced properties from the app azure module

---

azure/vnet/main.tf

small typo - refer naming conv

---

azure/resource-group/data.tf
azure/resource-group/variables.tf
azure/vnet/data.tf
azure/vnet/main.tf
azure/vnet/variables.tf

- add data
- filipe teste
- refactoring

nmbrs network service 003

---

azure/appservice-windows/local.tf
azure/appservice-windows/main.tf
azure/appservice-windows/variables.tf
azure/keyvault/local.tf
azure/keyvault/main.tf
azure/keyvault/variables.tf
azure/resource-group/data.tf
azure/resource-group/variables.tf
azure/storage_account/README.md
azure/storage_account/data.tf
azure/storage_account/main.tf
azure/storage_account/output.tf
azure/storage_account/terraform.tf
azure/storage_account/variables.tf

The goal of this PR is to revert unintended changes in the  following modules:
- keyvault
- app-service-windows
- resource-group
- storage-account
At the  PR #39, I had my code base outdated and merged old stuff from main branch that changed behaviors previously updated.
Please compare the reverted changes with the commit `952ead1`

revert(*): revert resource-group, storage-account, appservice-windows and keyvault changes

---

azure/storage_account/README.md
azure/storage_account/main.tf
azure/storage_account/terraform.tf
azure/storage_account/variables.tf

The idea of this PR was to remove data blocks, since we found issues using them if any data changes.
As we mentioned last week, when using data blocks, we have the issue of needing to employ 'depends on' statements, which means that every time data changes, the resource will be removed and recreated rather than just updated.
This PR corrects that by delegating the module's location and tags to whoever will use it. (in other words: added location and tags as variables.) 
Also:
- Updated variable descriptions to conform with the ones already used in other modules. (trying to follow the resource-group descriptions)
- Fixed `azurerm` provider version to 2.98.0 (ensuring that it will operate consistently, rather than relying on Azure developers to do the right thing with versioning)
- Enforced …

feat(storage-account): remove data block

---

.gitignore

The main goal of this PR is to update the `.gitignore` so we can ignore files unrelated to the code base. Here are some of the file types that weren't  covered before:
- The entire `terraform` folder
- all kinds of logs
- tmp files
- IDE files
- Snyk extension files

maint(*): update gitignore file

---

azure/keyvault/main.tf
azure/keyvault/output.tf
azure/keyvault/terraform.tf
azure/keyvault/variables.tf

The azure keyvault module is no longer setting secrets.
The module is only responsible for setting the keyvault and poicies. Content, like secrets/certificates/keys, are
setup through either manual or custom interfaces.
Code snippet used to validate the implementation.
⚠️ in the test snippet, the keyvault module is pointing to local module.
```hcl
module "heimdall_rg" {
source      = "git::github.com/Nmbrs/terraform-modules//azure/resource-group"
project     = "heimdall"
tags        = {
Country : "nl"
}
}
module "keyvault" {
source = "../tf-modules//azure/keyvault"
name                = "kv-heimdall"
tags        = { …
```

fix: removed secrets resource block, output and variables.

---

azure/keyvault/README.md

Add a README describing how to use the keyvault module with a sample.
Give developers an understanding on how the module works when implementing a service template.
n/a
n/a

doc: how to use keyvault module

---

azure/keyvault/main.tf

fixes #42
To close a security vulnerability found by tfsec and reported on #42.
- push branch to local environment
- make sure that keyvault module source value is pointing to the correct module path on local env
- copy/paste code snipped to a `main.tf`
```hcl
resource "azurerm_resource_group" "rg" {
name     = "rg-heimdall-dev"
tags = {
Country : "nl"
}
}
module "keyvault" {
source = "../tf-modules//azure/keyvault"
name                = "kv-nmbrs-heimdall-dev"
tags        = {
Country : "nl"
}
policies = {
admin = {
object_id = "7574db9b-72f3-431c-b068-b8769935e90c" …
```

fix: keyvault network access to Deny by default

---

azure/keyvault/local.tf
azure/keyvault/main.tf

Adds `terraform: created` tag to the key vault resource, to indicate that it was provisioned through terraform automation.  
To identify the resources that were provisioned through terraform automation from the others, for future migrations and service support.
- Push the branch to your local.
- copy/paste the code snippet to your local demo terraform main:
```hcl
resource "azurerm_resource_group" "rg" {
name     = "rg-heimdall-rg"
tags = {
Country : "nl"
}
}
module "keyvault" {
source = "../tf-modules//azure/keyvault"
name                = "kv-heimdall"
tags        = {
Country : "nl"
Environment : …
```

maint: added terraform key tag by default

---

azure/resource-group/README.md
azure/resource-group/main.tf
azure/resource-group/output.tf
azure/resource-group/variables.tf

1. Removed the prefix from the resource group name and renamed the variable from project to name as suits better.
2. Added tags to the output and modified all the names to follow the terraform provider convention.
3. Improve var description.
- push branch to your local environment
- copy/paste to a main.tf file
```hcl
module "rg" {
source   = "../tf-modules//azure/resource-group"
name     = "rg-heimdall-dev"
location = var.location
tags     = var.tags
}
output "rg_name" {
value = module.rg.name
}
output "rg_id" {
value = module.rg.id
}
output "rg_location" {
value = module.rg.location
}
output "rg_tags" {
value = module.rg.tags
}
```
- terraform init & terraform apply
- output
```diff
rg_id = "/subscriptions/0abe1f07-d2a2-4c7a-a36c-9e91baa7321d/resourceGroups/rg-heimdall-dev"
rg_location …
```

maint: small improvements

---

azure/keyvault/README.md

Replaced old object_id with invalid values.
This is a public repository, so any details must be invalid or blurred.
N/A
N/A

doc: added invalid object_id values

---

azure/storage_account/main.tf

To fix a tfsec warning check about the storage account logging.
Not only we close the security finding, but we also improve the storage account capabilities regarding logging.
- push the git branch to your local env.
- make sure that the source is pointing to local.
- copy/paste the following code to a main.tf file
```hcl
default = "westeurope"
}
default = "rg-heimdall-dev"
}
default = {
Country : "nl"
}
}
module "rg" {
source   = "../tf-modules//azure/resource-group"
name     = "rg-heimdall-dev"
location = var.location
tags     = var.tags
}
module "storage_account" {
source = "../tf-modules//azure/storage_account"
name                      = …
```

maint(storage-account): added logging settings

---

azure/appservice-windows/local.tf
azure/appservice-windows/main.tf
azure/appservice/local.tf
azure/appservice/main.tf
azure/keyvault/local.tf
azure/resource-group/local.tf
azure/resource-group/main.tf
azure/storage_account/local.tf
azure/storage_account/main.tf
azure/vnet/locals.tf
azure/vnet/main.tf
azure/windows-scaleset/local.tf

The `ManageBy` tag indicates how the resource is manage, either through Terraform or manually.
To support the hybrid situation that we have in Nmbrs.
- push the branch to your local.
- copy/paste
```hcl
default = "westeurope"
}
default = "rg-heimdall-dev"
}
variable "environment" {
default = "dev"
}
default = {
Country : "nl"
}
}
module "rg" {
source = "../tf-modules//azure/resource-group"
project     = "heimdall"
environment = var.environment
location = var.location
tags = var.tags
}
module "storage_account" {
source = "../tf-modules//azure/storage_account"
name                      = "sanmbrsheimdalldev"
resource_group_name       = var.resource_group_name …
```

maint: added ManageBy tag to missing modules

---

azure/appservice-windows/main.tf
azure/appservice-windows/output.tf
azure/custom-domain-binding/local.tf
azure/custom-domain-binding/main.tf
azure/custom-domain-binding/output.tf
azure/custom-domain-binding/provider.tf
azure/custom-domain-binding/terraform.tf
azure/custom-domain-binding/variables.tf

Creation of new module to take care of the SSL binding along with the DNS records
To allow the creation of DNS records and SSL binding on the app services.

Feature ssl binding

---

azure/keyvault/README.md
azure/keyvault/main.tf
azure/keyvault/variables.tf

This functionality fetches the azure ad `object_id` group through the security group name. The last one, is specified by the service template in a list format.
To make the module more accessible to developers when using it on the service template.
- push the branch to your local
- change the source to match the local file system
- copy/paste the following code to a _main.tf_
```hcl
#variables declaration
type = string
}
variable "module" {
type = string
}
type = string
}
variable "environment" {
type = string
}
default = {
Country : "nl"
}
}
module              = "heimdall"
environment …
```

feat: added support for azure ad security group name.

---

azure/keyvault/variables.tf

Added the missing delete right to both secret and certificate policies.
Be compliant with Nmbrs keyvault policies.
- push the branch to your local
- change the source to match the local file system
- copy/paste the following code to a _main.tf_
```hcl
#variables declaration
type = string
}
variable "module" {
type = string
}
type = string
}
variable "environment" {
type = string
}
default = {
Country : "nl"
}
}
module              = "heimdall"
environment         = "dev"
tags = {
Country : "NL"
Squad : "Infra"
Product : "Internal"
Environment : "Dev"
}
writers = ["SG-SquadInfra"]
readers …
```

fix: added delete right to both secret and certificate

---

azure/keyvault/main.tf
azure/keyvault/output.tf
azure/keyvault/terraform.tf
azure/keyvault/variables.tf

Enabling soft delete by-design is mandatory if we want to offer purge protection to the keyvault. Furthermore, there's a defined 7 days retention period.
The keyvaults contain sensitive information like secrets and certificates that can be deleted accidentally or by a bad actor. Adding protection option is then important, and it's configured on the service template based on environment.
- push the branch to your local.
- make sure that the keyvault source path is correct.
- copy/paste code snippet
```hcl
type = string
}
variable "module" {
type = string
}
type = string
}
variable "environment" {
type = string
}
default = {
Country : "nl"
}
}
variable "writers" …
```

feat (keyvault): added keyvault soft-delete and the option to enable purge protection.

---

.github/pull_request_template.yaml

This PR template was a remix based on the previous PR template that @fargozhu introduced and based on pr templates of two open source projects ([nestjs](https://github.com/nestjs/nest/blob/master/.github/PULL_REQUEST_TEMPLATE.md) and [angular](https://github.com/angular/angular/blob/master/.github/PULL_REQUEST_TEMPLATE.md)). Also, some customization related to terraform was added.
I've setup some PR templates like this one in the past and I think the checklist helps a lot, working as a big reminder to help simplify the code review process
**Note**: I've added this PR in the new format to exemplify how the new format should work
I've added this PR in the new format to show how it should work …

docs(pull_request_template): update pr template

---

azure/dns-records/output.tf

added outputs
Allow output the records being created

added outputs to the module

---

azure/resource-group/README.md
azure/resource-group/variables.tf

The main goal of this PR is to update the validation of the `environment` variable from the resource-group module. The environment should comply with the tagging strategy used at Nmbrs.
- Updated `Prod` value to Production
- Added `Kitchen` environment.
- Updated the `envrionment` values to be lowercase (otherwise we need to fix it on the modules that uses those variables)
1. At the root of the `tf-module` repository, create a `main.tf` file with the following code:
```hcl
terraform {
azurerm = {
}
}
}
features {
}
}
source      = …
```

fix(resource-group): update environment variable validation

---

azure/aks/README.md
azure/aks/main.tf
azure/aks/outputs.tf
azure/aks/variables.tf

This is a module required to build an AKS cluster.

adding aks module

---

azure/resource-group/README.md

The main goal of this PR is to update the README.md file of  the resource group making easier to understand how to reference modules provided from tf-module repository using git ref
Note: This update was based on feedback provided by @RuiEloiVisma
- Update to README.md:
- Changed local module reference to GitHub reference
- Changed the tags from to provide a better example
- Update the name of the resource
N/A

docs(resource_group): update README.md referencing the module using git

---

CODEOWNERS

By adding the CODEOWNER file to the repo, it will assure that determine users who have more responsibility and knowledge of the code repo are involved on the pull request review.
Check the file on GH portal for errors.

maint (general): added CODEOWNERS file.

---

azure/keyvault/README.md
azure/keyvault/main.tf
azure/keyvault/variables.tf

The main goal is to update keyvault policies to support managed identities, users, groups by providing objectids
update readers and writers policies to the following structure:
```hcl
variable "policies" {
description = "Define an Azure Key Vault access policy."
type = list(object({
name      = string
object_id = string
}))
default = []
}
```
Please test running the code below:
```hcl
terraform {
azurerm = {
}
}
}
features {
}
}
source      = "git::github.com/Nmbrs/tf-modules//azure/resource-group" …
```

refactor(keyvault): update kv policies

---

azure/appservice/local.tf
azure/appservice/main.tf
azure/dns-records/local.tf
azure/resource-group/local.tf
azure/storage_account/local.tf

Changed the key value of the local tags
The key value of terraform tag is the same as implemented in the keyvault

refactor(tags): changed tags local to be standard

---

azure/keyvault/main.tf

Change the retention period of the soft delete to allow for more days
Soft delete will remain for 31 days instead of 7

refactor(keyvault): changed soft delete retention days

---

azure/keyvault/README.md
azure/keyvault/variables.tf

The idea is to update the environment validation to support the following environments:
- dev
- test
- stag
- prod
Update supported environments 
1. Create a new tf file (main.tf for example) at the root of this repo in your working directory and add the code below referencing the 'keyvault' module
```hcl2
terraform {
azurerm = {
}
}
}
features {
}
}
source      = "./azure/resource-group"
environment = "Dev"
extra_tags = {
Datadog = "Monitored"
}
}
module …
```

feature(keyvault)!: update environment validation to support 'dev', 'test', 'stag' and 'prod'

---

azure/resource-group/README.md
azure/resource-group/variables.tf

The idea of this PR is to update the environment validation to support the following environments:
- dev
- test
- stag
- prod
- Updated the environment validation. Valid options are: `dev`, `test`, `stag` and `prod
1. Create a new tf file (main.tf for example) at the root of this repo in your working directory and add the code below referencing the 'resource-group' module
```hcl2
terraform {
azurerm = {
}
}
}
features {
}
}
squad       = …
```

feature(resource_group)!: update environment validation to support 'dev', 'test', 'stag' and 'prod'

---

.github/workflows/on-pull-request-security-scanning.workflow.yml

The main goal of this PR is to optimize the events that triggers the repo security scan workflow:
- The workflow will not be triggered in cases that the PR only contains changes in `*.md` files
- The workflow will not be triggered when the body or title of the PR were modified
- PRs are not triggered if the body or title of the PR is changed.
- ignore md files using a glob pattern
- Validate the `path-ignore` element by checking [github](https://docs.github.com/en/enterprise-server@3.1/actions/using-workflows/workflow-syntax-for-github-actions#onpushpull_requestpull_request_targetpathspaths-ignore) documentation
- Validate the glob pattern using …

ci(github): update pr security scan workflow

---

azure/app_service_windows/main.tf

Fix the version of the dependency on the custom domain module
Added the new version of the custom domain binding dependency inside the app service windows module
Start to use the new module tag

fix(custom_domain_binding)!: fix version custom domain dependency

---

azure/key_vault/variables.tf

The main goal of this PR is to add the environment `sand` to key_vault
1. At the root of the `tf-module` repository, create a `main.tf` file with the following code:`
```hcl
terraform {
azurerm = {
}
}
}
features {
}
}
name        = "heimadall-demo"
extra_tags = {
Datadog = "Monitored"
}
}
module "key_vault" {
source              = "./azure/key_vault"
name                = "Heimdall"
environment         = "sand" …
```

feature(keyvault): add sandbox environment

---

azure/dns_zone/terraform.tf

The main goal of this PR is to update the providers used in the `dns_zone` module:
- azurerm: https://registry.terraform.io/providers/hashicorp/azurerm/3.5.0
N/A
1. Create a new tf file (main.tf for example) at the root of this repo in your working directory and add the code below referencing the `key_vault`module
```hcl2
}
module "dns_zone" {
source              = "./azure/dns_zone"
name                = "api.live0.com"
resource_group_name = …
```

build(dns_zone): update azurerm and caf providers

---

azure/storage_account/terraform.tf

The main goal of this PR is to update the providers used in the `storage_account` module:
- azurerm: https://registry.terraform.io/providers/hashicorp/azurerm/3.6.0
N/A
1. Create a new tf file (main.tf for example) at the root of this repo in your working directory and add the code below referencing the `key_vault`module
```hcl2
}
module "storage_account" {
source              = "./azure/storage_account"
name                = "saPayrollStaginga4df" …
```

build(storage_account): update azurerm and caf providers

---

azure/storage_account/README.md
azure/storage_account/main.tf
azure/storage_account/terraform.tf
azure/storage_account/variables.tf

This pull request goal is to bring consistent between all azure resources when setting both location and tags, by loading that data from the resource group data block instead of handling as an input parameter.
There's no longer the need to specify the storage account, and both resource group and storage accounts are merged and duplications removed. 
1. clone the repo and checkout to the fix branch.
2. copy the follow code snippet to the _main.tf_
```hcl
module "rg" {
source = "git::github.com/Nmbrs/tf-modules//azure/resource_group?ref=main"
name        = "Heimdall"
country     = "NL"
squad       = "Infra"
product     = "Microservice Platform"
extra_tags = {
MonitoredOn = …
```

fix(storage-account)!: load location and tags from the resource group 

---

CODEOWNERS

The main goal of this pull request is to  update the CODEOWNERS  file. Since the @Nmbrs/squadinfra group was removed, we should replace it with the new team @Nmbrs/devops 

ci: update CODEOWERS file

---

azure/vnet/locals.tf
azure/vnet/main.tf
azure/vnet/outputs.tf
azure/vnet/terraform.tf

The main goal of this PR is to update the providers used in the vnet module:
- azurerm: https://registry.terraform.io/providers/hashicorp/azurerm/3.6.0
No behavioral changes
1 . Create a new tf file (main.tf for example) at the root of this repository in your working directory and add the code below referencing the `vnet` module
```hcl
terraform {
azurerm = {
version = "~> 3.0"
}
}
required_version = ">= 1.0.0, < 2.0.0"
}
features {
}
}
country …
```

build(resource_group): update azurerm and caf providers

---

github/repositories/main.tf

fix(github): change module indexes in tf state

---

github/repositories/main.tf
github/repositories/terraform.tf
github/repositories/variables.tf

The main goal of this PR is to add repository uniqueness validation, since the object  name in terraform state for each repository depends on its name uniqueness
As a secondary goal, this PR improves code indentation and parameter readability
- Add uniqueness validation for the property `name` in the elements of the repository list
```hcl
tterraform {
}
variable "github_token" {
sensitive = true
}
variable "github_owner" {
sensitive = true
default   = "nmbrs"
}
module "github_repository" {
source = …
```

feat(repositories): add github repositories name uniqueness validation

---

github/repositories/outputs.tf

The main goal of this PR is to add an array of repository outputs with relevant information that can be used in services and tooling systems.
Create a new tf file (main.tf for example) at the root of this repo in your working directory and add the code below:
```hcl
terraform {
}
variable "github_token" {
sensitive = true
}
variable "github_owner" {
sensitive = true
default   = "nmbrs"
}
module "github_repository" {
source = "./github/repositories"
github_token = var.github_token
github_owner = var.github_owner
repositories = [
{
"name" : "testing-repository",
"description" : "The best api to feed your ducks at home.", …
```

feat(repositories): add github repositories output

---

github/repositories/main.tf

The main goal of this PR is to remove the modify 
Since github [supports](https://docs.github.com/en/repositories/creating-and-managing-repositories/restoring-a-deleted-repository) restoring deleted repositories, this PR changes the current behavior of archiving repositories when they are deleted.
- The repository will not be archived when deleted.
Create a new tf file (main.tf for example) at the root of this repo in your working directory and add the code below:
```hcl
terraform {
}
variable "github_token" {
sensitive = true
}
variable "github_owner" {
sensitive = true
default   = "nmbrs"
}
module "github_repository" { …
```

feat(repository): remove archive_on_destroy behavior

---

azure/nat_gateway/main.tf
azure/nat_gateway/terraform.tf

Updated terraform provider AzureRM in Natgw and windows scale set
No new behavior
No need to test, nothing changes

fix(provider): update modules

---

azure/storage_account/main.tf
azure/storage_account/variables.tf

Use CAF in storage account
The name of storage account will be created using caf module

feature(caf): use caf to update storage account name

---

azure/resource_group/README.md

The main purpose of this pr is to update the kv documentation, so we can create a new release
N/A

feat(key_vault): update kv documetation

---

azure/storage_account/terraform.tf

The main goal of this PR is to update the Azure CAF provider, which was renamed from `2.0.0-preview-3` to `2.0.0-preview3"`. 
Note: A new updated stable release was created in the last month, according to the source [code](https://github.com/aztfmod/terraform-provider-azurecaf). Although it makes sense to use a stable release rather than a preview release, the change was delayed due to the need to change the terraform states that are already in place.
Update the renamed CAF [provider](https://github.com/aztfmod/terraform-provider-azurecaf) from version `2.0.0-preview-3` to `2.0.0-preview3"`
N/A

feat(storage_account): update caf provider

---

azure/dns_zone/terraform.tf

The main goal of this PR is to update the Azure CAF provider, which was renamed from `2.0.0-preview-3` to `2.0.0-preview3"`. 
Note: A new updated stable release was created in the last month, according to the source [code](https://github.com/aztfmod/terraform-provider-azurecaf). Although it makes sense to use a stable release rather than a preview release, the change was delayed due to the need to change the terraform states that are already in place.
Update the renamed CAF [provider](https://github.com/aztfmod/terraform-provider-azurecaf) from version `2.0.0-preview-3` to `2.0.0-preview3"`
N/A

feat(dns_zone): update caf provider

---

azure/resource_group/terraform.tf

The main goal of this PR is to update the Azure CAF provider, which was renamed from `2.0.0-preview-3` to `2.0.0-preview3"`. 
Note: A new updated stable release was created in the last month, according to the source [code](https://github.com/aztfmod/terraform-provider-azurecaf). Although it makes sense to use a stable release rather than a preview release, the change was delayed due to the need to change the terraform states that are already in place.
Update the renamed CAF [provider](https://github.com/aztfmod/terraform-provider-azurecaf) from version `2.0.0-preview-3` to `2.0.0-preview3"`
N/A

feat(resource_group): update caf provider

---

azure/virtual_network/local.tf

The main goal of this PR is to update the service delegations to follow the list of delegations available in the westeurope region
The list of delegations matches the current list of service delegations from West Europe region
In the cli run the command `az network vnet subnet list-available-delegations --location “westeurope”` and compare it with the delegation actions included in the `local.tf` file

fix(virtual_network): update service delegation acitons

---

azure/cosmo_db/local.tf
azure/cosmo_db/main.tf
azure/cosmo_db/terraform.tf
azure/cosmo_db/varaiables.tf

The main purpose of this PR is to add cosmo db module with basic settings.  The cosmo db module is initially for 'mongo db' database since that what we are using in Nmbrs. It can be modified later to support more types.
Added new cosmo db module for creating 'GlobalDocumentDB', 'MongoDB', 'Parse' DBs. For now the support is only for MongoDB.
```hcl
terraform {
azurerm = {
version = "~> 3.6"
}
}
}
features {
}
}
module "cosmo_db" {
source              = …
```

feat(cosmo_db): create new cosmo db module

---

azure/key_vault/README.md
azure/key_vault/terraform.tf
azure/key_vault/variables.tf

The main purpose of this PR is to remove the validation of the environment from the `key_vault` level. This change aims to transfer the responsibility of validating the environment and location to the Azure policies and the new modules location and environment. 
By implementing this change, we will make the key_vault more focused on its main purpose, and also make it less prone to errors by removing unnecessary validation code. This will also make it easier to maintain and understand the codebase in the long run.
- Removed the validation of the `envrionment` variable. …

feat(key_vault): remove environment validation

---

azure/storage_account/README.md
azure/storage_account/local.tf
azure/storage_account/main.tf
azure/storage_account/terraform.tf
azure/storage_account/variables.tf

The main purpose of this PR is to remove the logic provided to tag the resources within the module. This change will transfer the responsibility of validation from individual modules to the Azure policies, making the overall codebase more modular and maintainable. 
```hcl
terraform {
azurerm = {
version = "~> 3.6"
}
}
}
features {
}
}
name        = "pr_project"
location    = "westeurope"
environment …
```

feat(storage_account): remove tag logic

---

azure/dns_zone/README.md
azure/dns_zone/main.tf
azure/dns_zone/terraform.tf
azure/dns_zone/variables.tf

The main purpose of this PR is to remove the logic provided to tag the resources within the module. This change will transfer the responsibility of validation from individual modules to the Azure policies, making the overall codebase more modular and maintainable. 
```hcl
terraform {
azurerm = {
version = "~> 3.6"
}
}
}
features {
}
}
name        = "pr_project"
location    = "westeurope"
environment …
```

feat(dns_zone): remove tag logic from terraform

---

azure/nat_gateway/main.tf
azure/nat_gateway/terraform.tf

The main purpose of this PR is to remove the logic provided to tag the resources within the module. This change will transfer the responsibility of validation from individual modules to the Azure policies, making the overall codebase more modular and maintainable. 
N/A
N/A

feat(nat_gateway): remove tag logic from terraform

---

azure/virtual_network/README.md
azure/virtual_network/local.tf
azure/virtual_network/main.tf
azure/virtual_network/variables.tf

The main purpose of this PR is to remove the logic provided to tag the resources within the module. This change will transfer the responsibility of validation from individual modules to the Azure policies, making the overall codebase more modular and maintainable. 
```hcl
terraform {
azurerm = {
version = "~> 3.40"
}
}
}
features {
}
}
}
source   = …
```

feat(virtual_network): remove tag logic from terraform

---

azure/redis_cache/README.md
azure/redis_cache/local.tf
azure/redis_cache/main.tf
azure/redis_cache/outputs.tf
azure/redis_cache/terraform.tf
azure/redis_cache/variables.tf

This PR adds a new Terraform module for provisioning Azure Redis cache instances with ease. The module enforces minimum tier to premium and takes a single input variable, cache_size_gb, to determine the cache size and configure necessary parameters such as capacity, family, and sku_name. The module adheres to organization-specific policies and guidelines to ensure compliance and simplify the provisioning process for Redis cache instances. Additionally, the README.md file has been updated to include a detailed description of the module and its benefits.

feat(redis_cache): add redis cache module

---

azure/private_dns_zone/README.md
azure/private_dns_zone/main.tf
azure/private_dns_zone/output.tf
azure/private_dns_zone/terraform.tf
azure/private_dns_zone/variables.tf

The main goal of this PR is to create the Azure private DNS Zone module.
- Created the private DNS Zone Module
```hcl
terraform {
azurerm = {
version = "~> 3.40"
}
}
}
features {
}
}
}
}
name        = "pr_project"
location    = module.location.name …
```

feat(private_dns_zone): create private DNS Zone module

---

azure/virtual_network/README.md
azure/virtual_network/main.tf

The main goal of this pull request is to fix the `private_endpoint_network_policies_enabled` and `private_link_service_network_policies_enabled` parameters.
The bug can be spotted in the snippet below:
```hcl
private_endpoint_network_policies_enabled     = lookup(each.value, "private_link_service_network_policies_enabled", true)
private_link_service_network_policies_enabled = lookup(each.value, "private_endpoint_network_policies_enabled", true)
```

fix(virtual_network): fix private_endpoint_network_policies_enabled misplacement

---

azure/virtual_machine/terraform.tf

The main goal of this PR is to update random and tls providers, so it can accept minor changes updates
N/A
N/A
N/A
N/A

build(virtual_machine): update tls and random providers configuration

---

azure/dns_records/README.md

feat(dns-records): update  documentation 

---

azure/windows_scaleset/terraform.tf

feat(windows_scaleset): remove provider configs to allow the use of for_each loops

---

azure/virtual_network/terraform.tf

feat(virtual_network): remove provider configs to allow the use of for_each loops

---

azure/dns_records/terraform.tf

feat(dns_records): remove provider configs to allow the use of for_each loops

---

azure/cosmos_db/terraform.tf

feat(cosmos_db): remove provider configs to allow the use of for_each loops

---

azure/dns_zone/terraform.tf

feat(dns_zone): remove provider configs to allow the use of for_each loops

---

azure/private_dns_zone/terraform.tf

feat(private_dns_zone): remove provider configs to allow the use of for_each loops

---

azure/storage_account/terraform.tf

feat(storage_account): remove provider configs to allow the use of for_each loops

---

azure/virtual_machine/terraform.tf

feat(virtual_machine): remove provider configs to allow the use of for_each loops

---

azure/virtual_network/terraform.tf

The main goal of this PR is to remove caf module reference, since it's not being used
N/A
N/A
N/A

feature(vnet): remove caf resource reference

---

azure/service_bus/README.md
azure/service_bus/main.tf
azure/service_bus/output.tf
azure/service_bus/terraform.tf
azure/service_bus/variables.tf

feature(service): add service bus module

---

azure/service_bus/README.md
azure/service_bus/main.tf
azure/service_bus/output.tf
azure/service_bus/variables.tf

The main of goal is to update service bus validation and add naming concatenation
- [] Bugfix.

feature(service_bus): update service bus validation and add naming concatenation

---

azure/resource_group/README.md
azure/resource_group/terraform.tf

The main goal of this PR is to update terraform providers for the `resource_group` module

feature(resource_group): update terraform providers

---

azure/app_service/main.tf

Ignore app settings to eliminate the risk of deleting configurations that would cause the app service to malfunction
Ignore app settings to eliminate the risk of deleting configurations that would cause the app service to malfunction

feature(app_service): ignore app settings 

---

azure/location/README.md
azure/location/terraform.tf

The main goal of this PR is to update the terraform providers

feature(location): update terraform providers

---

azure/windows_scaleset/local.tf
azure/windows_scaleset/main.tf
azure/windows_scaleset/terraform.tf
azure/windows_scaleset/variables.tf

The main goal of this PR is to add the `location` parameter to the `windows_scaleset` module

feature(windows_scaleset): add location parameter

---

azure/log_analytics_workspace/README.md
azure/log_analytics_workspace/local.tf
azure/log_analytics_workspace/main.tf
azure/log_analytics_workspace/output.tf
azure/log_analytics_workspace/terraform.tf
azure/log_analytics_workspace/variables.tf

The main goal of this PR is to add a first version of the `log_analytics_workspace` module
- Added `log_analytics_workspace` module
```hcl
terraform {
azurerm = {
}
}
}
features {
}
}
}
}
name        = "pranalytics"
location …
```

feature(log_analytics_workspace): add log analytics workspace module

---

azure/redis_cache/README.md
azure/redis_cache/main.tf
azure/redis_cache/terraform.tf
azure/redis_cache/variables.tf

The main goal of this PR is to add the `location` parameter to the `redis_cache` module

feature(redis_cache): add location parameter

---

azure/virtual_network/README.md
azure/virtual_network/local.tf
azure/virtual_network/main.tf
azure/virtual_network/terraform.tf
azure/virtual_network/variables.tf

The main goal of this PR is to add the `location` parameter to the `virtual_network` module

feature(virtual_network): add location parameter

---

azure/private_dns_resolver/README.md
azure/private_dns_resolver/terraform.tf

The main goal of this PR is to update terraform providers for the `private_dns_resolver` module

feature(private_dns_resolver): update terraform providers

---

azure/private_dns_zone/README.md
azure/private_dns_zone/terraform.tf

The main goal of this PR is to update terraform providers for the `private_dns_zone` module

feature(private_dns_zone): update terraform providers

---

azure/virtual_network_peering/README.md
azure/virtual_network_peering/terraform.tf

The main goal of this PR is to update terraform providers for the `virtual_network_peering` module

feature(virtual_network_peering): update terraform providers

---

azure/virtual_machine/README.md
azure/virtual_machine/main.tf
azure/virtual_machine/terraform.tf
azure/virtual_machine/variables.tf

The main goal of this PR is to add the `location` parameter to the `virtual_machine` module

feature(virtual_machine): add location parameter

---

azure/storage_account/README.md
azure/storage_account/main.tf
azure/storage_account/terraform.tf
azure/storage_account/variables.tf

The main goal of this PR is to add environment and location parameters for the `storage_account` module
- Remove data provider for resource_groups
- Update documentation
- Removed data providers for the resour_group
- Added location parameter
- Environment parameter is now mandatory
```hcl
terraform {
azurerm = {
}
}
}
features {
}
}
}
source …
```

feature(storage_account): add location and environment parameters

---

azure/dns_records/README.md
azure/dns_records/terraform.tf

The main goal of this PR is to update terraform providers for the `dns_records` module

feature(dns_records): update terraform providers

---

azure/cosmos_db/README.md
azure/cosmos_db/local.tf
azure/cosmos_db/main.tf
azure/cosmos_db/terraform.tf
azure/cosmos_db/varaiables.tf

The main goal of this PR is to add the location parameters, fix variables and add a README.md to `cosmos_db` module
- Add location parameter
- Remove data provider for resource_groups
- Add documentation (README.md)
- Fix resource name
```hcl
terraform {
azurerm = {
}
}
}
features {
}
}
}
} …
```

feature(cosmos_db): add location and README.md

---

azure/dns_zone/README.md
azure/dns_zone/terraform.tf

The main goal of this PR is to update terraform providers for the `dns_zone` module

feature(dns_zone): update terraform providers

---

azure/application_insights/README.md
azure/application_insights/local.tf
azure/application_insights/main.tf
azure/application_insights/output.tf
azure/application_insights/terraform.tf
azure/application_insights/variables.tf

The main goal of this PR is to add the first version of the `application_insights` module
- Added the `application_insights` modules
```hcl
terraform {
azurerm = {
}
}
}
features {
}
}
}
}
name        = "pranalytics"
location …
```

feature(application_insights): add application_insights module

---

azure/service_bus/README.md
azure/service_bus/terraform.tf
azure/service_bus/variables.tf

The main goal of this PR is to update the `sku_name` parameter description

refactor(service_bus): update variable sku_name description

---

azure/redis_cache/README.md
azure/redis_cache/local.tf
azure/redis_cache/main.tf
azure/redis_cache/variables.tf

The main goal of this PR is to add support to the `Basic` and `Standard` tier
- Added support to `Basic` tier
- Added support to `Standard` tier
- Added `sku_name` parameter
- Improved validation between different tiers with preconditions
- Added the 0.25, 1 and 6 GB capacities for `Basic` and Standard tiers
```hcl
terraform {
azurerm = {
}
}
}
features {
}
}
} …
```

feature(redis_cache): add basic and standard tier support

---

azure/service_bus/README.md
azure/service_bus/main.tf
azure/service_bus/variables.tf

The main goal of this PR is to add support for the zone redundancy on the `service_bus` module
- Added the parameter zone_reduntant
- Added validations since zone_redundancy can only be enabled on the premium tier
```hcl
terraform {
azurerm = {
}
}
}
features {
}
}
}
}
module "resource_group" …
```

feature(service_bus): add zone redundancy capability

---

azure/private_dns_resolver/README.md
azure/private_dns_resolver/local.tf
azure/private_dns_resolver/main.tf
azure/private_dns_resolver/variables.tf

The main goal of this PR is to update the naming logic for the `private_dns-resolver`, enabling it to comply with the following rule:
- `dnspr-<application/workload><location><environment><###>`
- Added the `naming_sequential_number` parameter
```hcl
terraform {
azurerm = {
version = "~> 3.40"
}
}
}
features {
}
}
}
location = …
```

feature(private_dns_resolver): update module naming logic

---

azure/nat_gateway/README.md
azure/nat_gateway/local.tf
azure/nat_gateway/variables.tf

The main goal of this PR is to update public ip and nat gateway naming logic

feature(nat_gateway): update public ip and nat gateway naming logic

---

azure/managed_identity/README.md
azure/managed_identity/local.tf
azure/managed_identity/main.tf
azure/managed_identity/output.tf
azure/managed_identity/terraform.tf
azure/managed_identity/variables.tf

The main goal of this PR is to add the `manged_identity` module to the codebase
- Added a new event grid domain module
```hcl
terraform {
azurerm = {
}
}
}
features {
}
}
}
}
name        = "evgd-pr"
location    = …
```

feature(managed_identity): add managed identity module

---

azure/private_dns_zone/README.md
azure/private_dns_zone/main.tf
azure/private_dns_zone/terraform.tf

The main goal of this PR is to update the `private_dns_zone` VNet links, allowing the links to be applied, considering scenarios where the private DNS zone is not located within the same resource group as the linked virtual network.
- Removed the random provider to create the VNET link
- Updated the vnet link considering scenarios where the private DNS zone is not located within the same resource group as the linked virtual network.
```hcl
terraform {
azurerm = {
version = "~> 3.40"
}
}
required_version = ">= 1.3.0, < …
```

feature(private_dns_zone): update vnet link resource group

---

azure/key_vault/README.md
azure/key_vault/local.tf
azure/key_vault/main.tf
azure/key_vault/output.tf
azure/key_vault/variables.tf

The main goal of this PR is to remove the CAF module by updating the naming logic.

feature(key_vault): remove caf module by updating the naming logic

---

azure/app_service/main.tf

The main goal of this PR is to ignore the `auto-heal` and `ip-restriction` settings to ensure compatibility with changes done externally through the UI

feature(app_service): ignore auto heal and ip restriction settings

---

azure/storage_account/README.md
azure/storage_account/local.tf
azure/storage_account/main.tf
azure/storage_account/output.tf
azure/storage_account/variables.tf

The main goal of this PR is to remove the CAF module by updating the naming logic.

feature(storage_account): remove caf module by updating the naming logic

---

azure/resource_group/README.md

The main goal of this PR is to update  documentation examples to match the current development
N/A
N/A
N/A

docs(resource_group): fix module examples on README.md

---

azure/key_vault/terraform.tf

The main goal of this PR is to remove the unused CAF provider reference from the `key_vault` module
N/A
N/A

feature(key_vault): remove caf provider reference

---

azure/resource_group/README.md
azure/resource_group/local.tf
azure/resource_group/main.tf
azure/resource_group/output.tf
azure/resource_group/variables.tf

The main goal of this PR is to update `resource_group` replacing the parameter `name` in favor of the `workload`

feature(resource_group): replace name parameter in favor of workload

---

azure/key_vault/README.md
azure/key_vault/main.tf
azure/key_vault/output.tf
azure/key_vault/variables.tf

The main goal of this PR is to maintain support for the access policy control model while enabling the RBAC authorization mechanism in the key vaults.
- Added support to the RBAC authorization control using the variable `enable_rbac_authorization`
- maintained the support for the access policies using the `access_policies` object
- Added validations to ensure that the access_policies list will take effect only when the variable `enable_rbac_authorization` is set to false
```hcl
terraform {
azurerm = {
} …
```

feature(key_vault)!: add rbac authorization support

---

azure/app_service/main.tf

The main of this PR is to ignore the parameter `ip_restriction_default_action`
- ignored the parameter `ip_restriction_default_action`

feature(app_service): ignore ip restriction default action parameter

---

azure/app_service/main.tf

The main goal of this PR is to add the environment variable `ASPENETCORE_ENVIRONMENT` to the app service. The value that it assumes depends on the var `environmnet`:
- `environment` == dev then `ASPENETCORE_ENVIRONMENT` == Kitchen
- `environment` == test then `ASPENETCORE_ENVIRONMENT` == Test
- `environment` == prod then `ASPENETCORE_ENVIRONMENT` == Production
- `environment` == sand then `ASPENETCORE_ENVIRONMENT` == Sandbox
N/A
N/A
N/A

feature(app_service): add aspnet core environment variable configured by the environment

---

azure/key_vault/README.md
azure/key_vault/main.tf
azure/key_vault/variables.tf

The main goal of this PR is to include policies that matches administrators needs.
> Notes: The adminstrator role might be suitables for cases where purging and recovering secrets will be necessary or in cases when importing or backing up certificates is necessary

feature(key_vault): add adminstrators policy

---

azure/ssl_certificate/README.md
azure/ssl_certificate/local.tf
azure/ssl_certificate/main.tf
azure/ssl_certificate/terraform.tf
azure/ssl_certificate/variables.tf

The main goal of this PR is to add the SSL module
- Add `ssl_certificate` module
N/A

feature(ssl_certificate): add module

---

azure/private_endpoint/data.tf
azure/private_endpoint/local.tf
azure/private_endpoint/variables.tf

add new subresource to private endpoint

feature(private_endpoint): add new subresource to private endpoint

---

CHANGELOG.md
azure/cosmos_db/README.md
azure/cosmos_db/local.tf
azure/cosmos_db/main.tf
azure/cosmos_db/terraform.tf
azure/cosmos_db/variables.tf

add cosmo db module
add cosmo db module
```hcl
module "cosmos_mongo_db" {
source                            = "git::github.com/Nmbrs/tf-modules//azure/cosmos_db"
resource_group_name               = "rg-myapp"
workload                          = "mymongoserver"
environment                       = "dev"
location                          = "westeurope"
kind                              = "MongoDB"
mongo_db_version                  = "4.2"
instance_count                    = 1
public_network_access_enabled     = false
}
````

feature(cosmos_db): add cosmo db module

---

azure/application_gateway/README.md
azure/application_gateway/data.tf
azure/application_gateway/main.tf
azure/application_gateway/variables.tf

add waf policy flag
add waf policy flag

feature(application-gateway): add waf policy

---

azure/private_endpoint/data.tf
azure/private_endpoint/local.tf
azure/private_endpoint/terraform.tf
azure/private_endpoint/variables.tf

The main goal of this PR is to include support to `redis_cache` at the private endpoint module

feature(private_endpoint): add redis cache support

---

azure/redis_cache/README.md
azure/redis_cache/main.tf
azure/redis_cache/variables.tf

The main goal of this PR is to add a public network access flag set as false by default

feature(redis_cache): add public network flag redis

---

azure/event_hub/README.md
azure/event_hub/local.tf
azure/event_hub/main.tf
azure/event_hub/terraform.tf
azure/event_hub/variable.tf

Add a module to allow the creation of event_hubs
```hcl
module "event_hub" {
source   = "git::github.com/Nmbrs/tf-modules//azure/event_hub"
workload                 = "event_hub_name"
environment              = "dev"
location                 = "westeurope"
resource_group_name      = "rg-myrg"
capacity                 = "1"
auto_inflate_enabled     = true
maximum_throughput_units = 2
sku                      = "Standard"
event_hubs_settings = [
{
name = "hub-name1"
consumer_groups = [
{
name = "consumer-group1"
partition_count = 4
message_retention = 7
}
]
authorization_rules = [
{
name = "auth-rule-name"
listen = true
send = false
manage = false
}
]
},
{
name = "hub-name2"
consumer_groups = …
```

feature(event_hub): add event_hub module

---

azure/service_bus/README.md
azure/service_bus/main.tf
azure/service_bus/terraform.tf
azure/service_bus/variables.tf

The main goal of this PR is to remove the system assigned implementation from the modules as it's not used.

feature(servcie_bus): remove system assigned identity implementation

---

azure/private_endpoint/README.md
azure/private_endpoint/data.tf
azure/private_endpoint/local.tf
azure/private_endpoint/main.tf
azure/private_endpoint/terraform.tf
azure/private_endpoint/variables.tf

The main goal of this PR is to add a logic to configure private DNS Zones using resource IDs , allowing cross subscription implementations

feature(private_endpoint): support private dns zone id logic

---

azure/cdn_frontdoor/README.md
azure/cdn_frontdoor/data.tf
azure/cdn_frontdoor/local.tf
azure/cdn_frontdoor/main.tf
azure/cdn_frontdoor/terraform.tf
azure/cdn_frontdoor/variables.tf

The main goal of this PR is to add the `cdn_frontdoor` module to be used for content delivery

feature(cdn_frontdoor): add module

---

.pre-commit-config.yaml

The main goal of this PR is to add pre-commit configuration files
N/A
N/A

ci(pre-commit): add config file

---

terraformcloud/project/README.md
terraformcloud/project/data.tf
terraformcloud/project/main.tf
terraformcloud/project/terraform.tf
terraformcloud/project/variables.tf

The main goal of this PR is to add terraform cloud project module so it can be reused across multiple workspaces in a simplified way by associating it with variable sets to provide inherited credentials from the organizational level

feature(terraformcloud_project): add module

---

azure/dns_zone/terraform.tf

ci(dns_zone): bump and fix provider versions

---

terraformcloud/workspace/terraform.tf

ci(workspace): bump and fix provider versions

---

terraformcloud/variable_set/terraform.tf

ci(variable_set): bump and fix provider versions

---

terraformcloud/project/terraform.tf

ci(project): bump and fix provider versions

---

terraformcloud/organization/terraform.tf

ci(organization): bump and fix provider versions

---

azure/windows_scaleset/terraform.tf

ci(windows_scaleset): bump and fix provider versions

---

azure/vpn_gateway/terraform.tf

ci(vpn_gateway): bump and fix provider versions

---

azure/virtual_network_peering/terraform.tf

ci(virtual_network_peering): bump and fix provider versions

---

azure/virtual_machine/terraform.tf

ci(virtual_machine): bump and fix provider versions

---

azure/ssl_certificate/terraform.tf

ci(ssl_certificate): bump and fix provider versions

---

azure/sql_server/terraform.tf

ci(sql_server): bump and fix provider versions

---

azure/sql_database/terraform.tf

ci(sql_database): bump and fix provider versions

---

azure/resource_group/terraform.tf

ci(resource_group): bump and fix provider versions

---

azure/redis_cache/terraform.tf

ci(redis_cache): bump and fix provider versions

---

azure/private_dns_resolver/terraform.tf

ci(private_dns_resolver): bump and fix provider versions

---

azure/nat_gateway/terraform.tf

ci(nat_gateway): bump and fix provider versions

---

azure/managed_identity/terraform.tf

ci(managed_identity): bump and fix provider versions

---

azure/log_analytics_workspace/terraform.tf

ci(log_analytics_workspace): bump and fix provider versions

---

azure/key_vault/terraform.tf

ci(key_vault): bump and fix provider versions

---

azure/event_hub/terraform.tf

ci(event_hub): bump and fix provider versions

---

azure/dns_records/terraform.tf

ci(dns_records): bump and fix provider versions

---

azure/cosmos_db/terraform.tf

ci(cosmos_db): bump and fix provider versions

---

azure/app_service/terraform.tf

ci(app_service): bump and fix provider versions

---

azure/application_insights/terraform.tf

ci(application_insights): bump and fix provider versions

---

azure/ssl_certificate/README.md
azure/ssl_certificate/main.tf
azure/ssl_certificate/variables.tf

The main goal of this PR is to allow the usage of override name parameter in the module

feature(sslcertificates): add override name parameter

---

azure/document_intelligence/main.tf
azure/document_intelligence/variable.tf

fix(documentintelligence): fixed changed to allow autoscale and custom domain

---

azure/key_vault/local.tf
azure/key_vault/variables.tf
azure/ssl_certificate/README.md

feature(key_vault): allow override naming convention

---

github/team/data.tf
github/team/main.tf
github/team/terraform.tf
github/team/variables.tf

The main goal of this PR is to add the github team module so we can control in an organizational level, permissions associated
- Add github team module

feature(github-module): add module

---

azure/private_endpoint/README.md
azure/private_endpoint/data.tf
azure/private_endpoint/local.tf
azure/private_endpoint/variables.tf

add api management private endpoint

feature(private_endpoint): add api management private endpoint

---

azure/storage_account/main.tf
azure/storage_account/variables.tf

This PR introduces the implementation of the `trusted_services_bypass_firewall_enabled ` variable in the Storage Account module to allow trusted Microsoft services to bypass network firewall restrictions.

feature(storage_account): allow azure services to bypass network firewall
